[versions]
agp = "8.11.1"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin = "2.2.0"
mockk = "1.14.5"

[libraries]
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[bundles]

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "maven-publish" }