[versions]
agp = "8.12.0"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.0"
mockk = "1.14.5"
timber = "5.0.1"

[libraries]
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[bundles]

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "maven-publish" }